# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'EmptyDataSet-Swift', '= 5.0.0'
  #  pod 'R.Swift'
  pod 'MBProgressHUD'

  # Pods for RxSwiftProject

end
